version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
                [
                  "subnet-0b365b3de0b0452d3",
                  "subnet-0a2caaecfe4613410",
                ]
            SecurityGroups: ["sg-0bdafdeb68b407056"]
            AssignPublicIp: "DISABLED"
