version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
                [
                  "subnet-08a167deac10adc56",
                  "subnet-0137dd0b6137e107b",
                ]
            SecurityGroups: ["sg-020eb18f60325aae5"]
            AssignPublicIp: "DISABLED"
